import React, { createContext, useContext, useState } from 'react';

export type Language = 'uz' | 'ru' | 'en' | 'ko';

export const translations = {
  uz: {
    home: 'Bosh sahifa', projects: 'Loyihalar', services: 'Xizmatlar', courses: 'Kurslarim', resume: 'Rezyume', contact: 'Aloqa',
    yearsExp: 'Yil Tajriba', projectsCount: 'Loyihalar', clients: 'Mijozlar', certs: 'Sertifikatlar',
    aiChat: 'AI Yordamchi', blog: 'Blog', lang: 'Til', connect: 'Tarmoqlar',
    projectsTitle: 'Mening Loyihalarim', projectsDesc: 'Eng so\'nggi va sara ishlarim to\'plami',
    servicesTitle: 'Xizmatlar', servicesDesc: 'Sizning biznesingiz uchun raqamli yechimlar',
    coursesTitle: 'Kurslar', coursesDesc: 'Zamonaviy kasblarni biz bilan o\'rganing',
    resumeTitle: 'Rezyume', resumeDesc: 'Mening tajribam va malakam',
    contactTitle: 'Aloqa', contactDesc: 'Men bilan bog\'lanish uchun xabar qoldiring',
    videoTitle: 'Mening 3D Videoyim',
    selectLang: 'Tilni tanlang',
    send: 'Yuborish',
    message: 'Xabar yozing...',
    aiGreeting: 'Salom! Men Sarvarning AI yordamchisiman. Sizga qanday yordam bera olaman?',
    comment: 'Fikr bildirish',
    post1Title: 'Yangi loyiha ustida ishlayapman', post1Date: 'Bugun, 14:30', post1Content: 'React va Three.js yordamida yangi 3D portfolio yaratyapman. Natijalar ajoyib!',
    post2Title: 'AI kelajagi', post2Date: 'Kecha, 09:15', post2Content: 'Sun\'iy intellekt dasturlashni qanday o\'zgartirayotgani haqida o\'ylardim...',
    post3Title: 'Framer Motion darsi', post3Date: '2 kun oldin', post3Content: 'Animatsiyalar yaratish bo\'yicha yangi video darslik tayyorladim.',
    stat1Desc: 'Frontend Development, UI/UX Design, Backend Node.js',
    stat2Desc: 'E-commerce platforma, CRM tizimlar, Portfolio saytlar',
    stat3Desc: 'Mahalliy korxonalar, Xalqaro startaplar, Agentliklar',
    stat4Desc: 'Google UX Design, Meta Front-End, AWS Cloud, IELTS',
    statIndicator: 'ko\'rsatkich',
    statDetail: 'Batafsil ma\'lumot bu yerda yoziladi...',
    namePlaceholder: 'Ismingiz',
    emailPlaceholder: 'Email',
    subjectPlaceholder: 'Mavzu',
    resumeRole: 'Senior Frontend Developer',
    resumeCompany: 'Tech Company',
    resumeDetail: 'Katta hajmdagi loyihalarni boshqarish va jamoa bilan ishlash tajribasi. React, TypeScript va Node.js texnologiyalaridan foydalanish.',
    courseLessons: 'Dars',
    courseCert: 'Sertifikat',
    courseDesc: 'React va zamonaviy texnologiyalar orqali to\'liq kurs.',
    serviceWeb: 'Web Development', serviceWebDesc: 'Modern va tezkor veb saytlar',
    serviceMobile: 'Mobile Apps', serviceMobileDesc: 'iOS va Android ilovalar',
    serviceUI: 'UI/UX Design', serviceUIDesc: 'Foydalanuvchi uchun qulay dizayn',
    serviceBackend: 'Backend Systems', serviceBackendDesc: 'Node.js va Python arxitekturasi',
    projectTech: 'React, Three.js, TailwindCSS',
    present: 'Hozirgacha',
    letsConnect: 'Tarmoqlar',
    phone: 'Telefon',
    socials: 'Ijtimoiy tarmoqlar',
    close: 'Yopish',
    aiThinking: 'O\'ylayapman...',
  },
  en: {
    home: 'Home', projects: 'Projects', services: 'Services', courses: 'Courses', resume: 'Resume', contact: 'Contact',
    yearsExp: 'Years Exp', projectsCount: 'Projects', clients: 'Clients', certs: 'Certificates',
    aiChat: 'AI Chat', blog: 'Blog', lang: 'Language', connect: 'Networks',
    projectsTitle: 'My Projects', projectsDesc: 'Collection of my latest and best works',
    servicesTitle: 'Services', servicesDesc: 'Digital solutions for your business',
    coursesTitle: 'Courses', coursesDesc: 'Learn modern professions with us',
    resumeTitle: 'Resume', resumeDesc: 'My experience and qualifications',
    contactTitle: 'Contact', contactDesc: 'Leave a message to get in touch',
    videoTitle: 'My 3D Video',
    selectLang: 'Select Language',
    send: 'Send',
    message: 'Type a message...',
    aiGreeting: 'Hello! I am Sarvar\'s AI assistant. How can I help you?',
    comment: 'Comment',
    post1Title: 'Working on a new project', post1Date: 'Today, 14:30', post1Content: 'Creating a new 3D portfolio using React and Three.js. The results are amazing!',
    post2Title: 'The future of AI', post2Date: 'Yesterday, 09:15', post2Content: 'Thinking about how Artificial Intelligence is changing programming...',
    post3Title: 'Framer Motion tutorial', post3Date: '2 days ago', post3Content: 'Prepared a new video tutorial on creating animations.',
    stat1Desc: 'Frontend Development, UI/UX Design, Backend Node.js',
    stat2Desc: 'E-commerce platforms, CRM systems, Portfolio sites',
    stat3Desc: 'Local businesses, International startups, Agencies',
    stat4Desc: 'Google UX Design, Meta Front-End, AWS Cloud, IELTS',
    statIndicator: 'indicator',
    statDetail: 'Detailed information will be written here...',
    namePlaceholder: 'Your Name',
    emailPlaceholder: 'Email',
    subjectPlaceholder: 'Subject',
    resumeRole: 'Senior Frontend Developer',
    resumeCompany: 'Tech Company',
    resumeDetail: 'Experience managing large-scale projects and working with teams. Using React, TypeScript, and Node.js technologies.',
    courseLessons: 'Lessons',
    courseCert: 'Certificate',
    courseDesc: 'Full course on React and modern technologies.',
    serviceWeb: 'Web Development', serviceWebDesc: 'Modern and fast websites',
    serviceMobile: 'Mobile Apps', serviceMobileDesc: 'iOS and Android applications',
    serviceUI: 'UI/UX Design', serviceUIDesc: 'User-friendly design',
    serviceBackend: 'Backend Systems', serviceBackendDesc: 'Node.js and Python architecture',
    projectTech: 'React, Three.js, TailwindCSS',
    present: 'Present',
    letsConnect: 'Networks',
    phone: 'Phone',
    socials: 'Social Networks',
    close: 'Close',
    aiThinking: 'Thinking...',
  },
  ru: {
    home: 'Главная', projects: 'Проекты', services: 'Услуги', courses: 'Курсы', resume: 'Резюме', contact: 'Контакты',
    yearsExp: 'Лет опыта', projectsCount: 'Проекты', clients: 'Клиенты', certs: 'Сертификаты',
    aiChat: 'ИИ Чат', blog: 'Блог', lang: 'Язык', connect: 'Сети',
    projectsTitle: 'Мои Проекты', projectsDesc: 'Коллекция моих лучших работ',
    servicesTitle: 'Услуги', servicesDesc: 'Цифровые решения для вашего бизнеса',
    coursesTitle: 'Курсы', coursesDesc: 'Изучайте современные профессии с нами',
    resumeTitle: 'Резюме', resumeDesc: 'Мой опыт и квалификация',
    contactTitle: 'Контакты', contactDesc: 'Оставьте сообщение, чтобы связаться',
    videoTitle: 'Мое 3D Видео',
    selectLang: 'Выберите язык',
    send: 'Отправить',
    message: 'Напишите сообщение...',
    aiGreeting: 'Привет! Я ИИ-помощник Сарвара. Чем могу помочь?',
    comment: 'Комментировать',
    post1Title: 'Работаю над новым проектом', post1Date: 'Сегодня, 14:30', post1Content: 'Создаю новое 3D портфолио с помощью React и Three.js. Результаты потрясающие!',
    post2Title: 'Будущее ИИ', post2Date: 'Вчера, 09:15', post2Content: 'Думаю о том, как искусственный интеллект меняет программирование...',
    post3Title: 'Урок по Framer Motion', post3Date: '2 дня назад', post3Content: 'Подготовил новый видеоурок по созданию анимаций.',
    stat1Desc: 'Frontend Development, UI/UX Design, Backend Node.js',
    stat2Desc: 'E-commerce платформы, CRM системы, Сайты портфолио',
    stat3Desc: 'Местные компании, Международные стартапы, Агентства',
    stat4Desc: 'Google UX Design, Meta Front-End, AWS Cloud, IELTS',
    statIndicator: 'показатель',
    statDetail: 'Подробная информация будет написана здесь...',
    namePlaceholder: 'Ваше имя',
    emailPlaceholder: 'Email',
    subjectPlaceholder: 'Тема',
    resumeRole: 'Senior Frontend Developer',
    resumeCompany: 'Tech Company',
    resumeDetail: 'Опыт управления крупными проектами и работы в команде. Использование технологий React, TypeScript и Node.js.',
    courseLessons: 'Уроков',
    courseCert: 'Сертификат',
    courseDesc: 'Полный курс по React и современным технологиям.',
    serviceWeb: 'Web Development', serviceWebDesc: 'Современные и быстрые сайты',
    serviceMobile: 'Mobile Apps', serviceMobileDesc: 'Приложения для iOS и Android',
    serviceUI: 'UI/UX Design', serviceUIDesc: 'Удобный для пользователя дизайн',
    serviceBackend: 'Backend Systems', serviceBackendDesc: 'Архитектура Node.js и Python',
    projectTech: 'React, Three.js, TailwindCSS',
    present: 'По настоящее время',
    letsConnect: 'Сети',
    phone: 'Телефон',
    socials: 'Социальные сети',
    close: 'Закрыть',
    aiThinking: 'Думаю...',
  },
  ko: {
    home: '홈', projects: '프로젝트', services: '서비스', courses: '코스', resume: '이력서', contact: '연락처',
    yearsExp: '경력(년)', projectsCount: '프로젝트', clients: '고객', certs: '인증서',
    aiChat: 'AI 채팅', blog: '블로그', lang: '언어', connect: '네트워크',
    projectsTitle: '내 프로젝트', projectsDesc: '나의 최신 및 최고 작품 모음',
    servicesTitle: '서비스', servicesDesc: '귀하의 비즈니스를 위한 디지털 솔루션',
    coursesTitle: '코스', coursesDesc: '우리와 함께 현대 직업을 배우십시오',
    resumeTitle: '이력서', resumeDesc: '나의 경험과 자격',
    contactTitle: '연락처', contactDesc: '연락하려면 메시지를 남겨주세요',
    videoTitle: '내 3D 비디오',
    selectLang: '언어 선택',
    send: '보내기',
    message: '메시지 입력...',
    aiGreeting: '안녕하세요! 저는 Sarvar의 AI 어시스턴트입니다. 무엇을 도와드릴까요?',
    comment: '댓글',
    post1Title: '새 프로젝트 작업 중', post1Date: '오늘, 14:30', post1Content: 'React와 Three.js를 사용하여 새로운 3D 포트폴리오를 만들고 있습니다.',
    post2Title: 'AI의 미래', post2Date: '어제, 09:15', post2Content: '인공 지능이 프로그래밍을 어떻게 변화시키고 있는지 생각 중...',
    post3Title: 'Framer Motion 튜토리얼', post3Date: '2일 전', post3Content: '애니메이션 제작에 대한 새로운 비디오 튜토리얼을 준비했습니다.',
    stat1Desc: '프론트엔드 개발, UI/UX 디자인, 백엔드 Node.js',
    stat2Desc: '전자 상거래 플랫폼, CRM 시스템, 포트폴리오 사이트',
    stat3Desc: '지역 기업, 국제 스타트업, 대행사',
    stat4Desc: 'Google UX Design, Meta Front-End, AWS Cloud, IELTS',
    statIndicator: '지표',
    statDetail: '자세한 정보는 여기에 작성됩니다...',
    namePlaceholder: '이름',
    emailPlaceholder: '이메일',
    subjectPlaceholder: '주제',
    resumeRole: '수석 프론트엔드 개발자',
    resumeCompany: '기술 회사',
    resumeDetail: '대규모 프로젝트 관리 및 팀과의 협업 경험.',
    courseLessons: '강의',
    courseCert: '인증서',
    courseDesc: 'React 및 최신 기술에 대한 전체 과정.',
    serviceWeb: '웹 개발', serviceWebDesc: '현대적이고 빠른 웹사이트',
    serviceMobile: '모바일 앱', serviceMobileDesc: 'iOS 및 Android 애플리케이션',
    serviceUI: 'UI/UX 디자인', serviceUIDesc: '사용자 친화적인 디자인',
    serviceBackend: '백엔드 시스템', serviceBackendDesc: 'Node.js 및 Python 아키텍처',
    projectTech: 'React, Three.js, TailwindCSS',
    present: '현재',
    letsConnect: '네트워크',
    phone: '전화',
    socials: '소셜 네트워크',
    close: '닫기',
    aiThinking: '생각 중...',
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations['uz']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('uz');
  const t = (key: keyof typeof translations['uz']) => translations[lang][key] || translations['uz'][key];
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
